version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=021891615384.dkr.ecr.ap-south-1.amazonaws.com/pvn-studentservice
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      
      # Define container names
      - DOCKER_CONTAINER_NAME_1=course-service
      - DOCKER_CONTAINER_NAME_2=pvn-studentservice

      # Writing image definitions for both containers
      - printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' \
        $DOCKER_CONTAINER_NAME_1 $REPOSITORY_URI:$IMAGE_TAG \
        $DOCKER_CONTAINER_NAME_2 $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

      - echo Image definitions file content:
      - cat imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
    - target/course-service.jar

